---
beam_rider:
  - env-beamrider_n-1_m-2500_batchmode-False
  - env-beamrider_n-1_m-2500_batchmode-True
  - env-beamrider_n-1_m-7500_batchmode-False
  - env-beamrider_n-1_m-12500_batchmode-False
  - env-beamrider_n-1_m-17500_batchmode-False
  - env-beamrider_n-3_m-2500_batchmode-False
  - env-beamrider_n-3_m-2500_batchmode-True
  - env-beamrider_n-3_m-7500_batchmode-False
  - env-beamrider_n-3_m-12500_batchmode-False
  - env-beamrider_n-3_m-17500_batchmode-False
  - env-beamrider_n-5_m-2500_batchmode-False
  - env-beamrider_n-5_m-2500_batchmode-True
  - env-beamrider_n-5_m-7500_batchmode-False
  - env-beamrider_n-5_m-12500_batchmode-False
  - env-beamrider_n-5_m-17500_batchmode-False
  - env-beamrider_n-7_m-2500_batchmode-False
  - env-beamrider_n-7_m-2500_batchmode-True
  - env-beamrider_n-7_m-7500_batchmode-False
  - env-beamrider_n-7_m-12500_batchmode-False
  - env-beamrider_n-7_m-17500_batchmode-False
breakout:
  - env-breakout_n-1_m-2500_batchmode-False
  - env-breakout_n-1_m-2500_batchmode-True
  - env-breakout_n-1_m-7500_batchmode-False
  - env-breakout_n-1_m-12500_batchmode-False
  - env-breakout_n-1_m-17500_batchmode-False
  - env-breakout_n-3_m-2500_batchmode-False
  - env-breakout_n-3_m-2500_batchmode-True
  - env-breakout_n-3_m-7500_batchmode-False
  - env-breakout_n-3_m-12500_batchmode-False
  - env-breakout_n-3_m-17500_batchmode-False
  - env-breakout_n-5_m-2500_batchmode-False
  - env-breakout_n-5_m-2500_batchmode-True
  - env-breakout_n-5_m-7500_batchmode-False
  - env-breakout_n-5_m-12500_batchmode-False
  - env-breakout_n-5_m-17500_batchmode-False
  - env-breakout_n-7_m-2500_batchmode-False
  - env-breakout_n-7_m-2500_batchmode-True
  - env-breakout_n-7_m-7500_batchmode-False
  - env-breakout_n-7_m-12500_batchmode-False
  - env-breakout_n-7_m-17500_batchmode-False
space_invaders:
  - env-spaceinvaders_n-1_m-2500_batchmode-False
  - env-spaceinvaders_n-1_m-2500_batchmode-True
  - env-spaceinvaders_n-1_m-7500_batchmode-False
  - env-spaceinvaders_n-1_m-12500_batchmode-False
  - env-spaceinvaders_n-1_m-17500_batchmode-False
  - env-spaceinvaders_n-3_m-2500_batchmode-False
  - env-spaceinvaders_n-3_m-2500_batchmode-True
  - env-spaceinvaders_n-3_m-7500_batchmode-False
  - env-spaceinvaders_n-3_m-12500_batchmode-False
  - env-spaceinvaders_n-3_m-17500_batchmode-False
  - env-spaceinvaders_n-5_m-2500_batchmode-False
  - env-spaceinvaders_n-5_m-2500_batchmode-True
  - env-spaceinvaders_n-5_m-7500_batchmode-False
  - env-spaceinvaders_n-5_m-12500_batchmode-False
  - env-spaceinvaders_n-5_m-17500_batchmode-False
  - env-spaceinvaders_n-7_m-2500_batchmode-False
  - env-spaceinvaders_n-7_m-2500_batchmode-True
  - env-spaceinvaders_n-7_m-7500_batchmode-False
  - env-spaceinvaders_n-7_m-12500_batchmode-False
  - env-spaceinvaders_n-7_m-17500_batchmode-False
seaquest:
  - env-seaquest_n-1_m-2500_batchmode-False
  - env-seaquest_n-1_m-2500_batchmode-True
  - env-seaquest_n-1_m-7500_batchmode-False
  - env-seaquest_n-1_m-12500_batchmode-False
  - env-seaquest_n-1_m-17500_batchmode-False
  - env-seaquest_n-3_m-2500_batchmode-False
  - env-seaquest_n-3_m-2500_batchmode-True
  - env-seaquest_n-3_m-7500_batchmode-False
  - env-seaquest_n-3_m-12500_batchmode-False
  - env-seaquest_n-3_m-17500_batchmode-False
  - env-seaquest_n-5_m-2500_batchmode-False
  - env-seaquest_n-5_m-2500_batchmode-True
  - env-seaquest_n-5_m-7500_batchmode-False
  - env-seaquest_n-5_m-12500_batchmode-False
  - env-seaquest_n-5_m-17500_batchmode-False
  - env-seaquest_n-7_m-2500_batchmode-False
  - env-seaquest_n-7_m-2500_batchmode-True
  - env-seaquest_n-7_m-7500_batchmode-False
  - env-seaquest_n-7_m-12500_batchmode-False
  - env-seaquest_n-7_m-17500_batchmode-False
pong:
  - env-pong_n-1_m-2500_batchmode-False
  - env-pong_n-1_m-2500_batchmode-True
  - env-pong_n-1_m-7500_batchmode-False
  - env-pong_n-1_m-12500_batchmode-False
  - env-pong_n-1_m-17500_batchmode-False
  - env-pong_n-3_m-2500_batchmode-False
  - env-pong_n-3_m-2500_batchmode-True
  - env-pong_n-3_m-7500_batchmode-False
  - env-pong_n-3_m-12500_batchmode-False
  - env-pong_n-3_m-17500_batchmode-False
  - env-pong_n-5_m-2500_batchmode-False
  - env-pong_n-5_m-2500_batchmode-True
  - env-pong_n-5_m-7500_batchmode-False
  - env-pong_n-5_m-12500_batchmode-False
  - env-pong_n-5_m-17500_batchmode-False
  - env-pong_n-7_m-2500_batchmode-False
  - env-pong_n-7_m-2500_batchmode-True
  - env-pong_n-7_m-7500_batchmode-False
  - env-pong_n-7_m-12500_batchmode-False
  - env-pong_n-7_m-17500_batchmode-False
...
