---
hp_search:
  xmetric: timestep
  ymetric: avg_return
  xlim: [0, 15000000]
  ylog: False
  xlabel: Timesteps
  ylabel: Score
  labels: ["Classic DQN", "2-strap DQN", "3-strap DQN", "4-strap DQN"]
  colors: [black, tab:blue, tab:green, tab:orange]
  plots:
    beamrider_n-3:
      title: Beam Rider
      experiments:
        - env-beamrider_n-3_m-0
        - env-beamrider_n-3_m-2
        - env-beamrider_n-3_m-3
        - env-beamrider_n-3_m-4
    breakout_n-3:
      title: Breakout
      experiments:
        - env-breakout_n-3_m-0
        - env-breakout_n-3_m-2
        - env-breakout_n-3_m-3
        - env-breakout_n-3_m-4
    pong_n-3:
      title: Pong
      experiments:
        - env-pong_n-3_m-0
        - env-pong_n-3_m-2
        - env-pong_n-3_m-3
        - env-pong_n-3_m-4
    seaquest_n-3:
      title: Seaquest
      experiments:
        - env-seaquest_n-3_m-0
        - env-seaquest_n-3_m-2
        - env-seaquest_n-3_m-3
        - env-seaquest_n-3_m-4
    spaceinvaders_n-3:
      title: Space Invaders
      experiments:
        - env-spaceinvaders_n-3_m-0
        - env-spaceinvaders_n-3_m-2
        - env-spaceinvaders_n-3_m-3
        - env-spaceinvaders_n-3_m-4
...
