---
beam_rider:
  - env-beamrider_n-2_batchmode-True
  - env-beamrider_n-3_batchmode-True
  - env-beamrider_n-4_batchmode-True
breakout:
  - env-breakout_n-2_batchmode-True
  - env-breakout_n-3_batchmode-True
  - env-breakout_n-4_batchmode-True
centipede:
  - env-centipede_n-2_batchmode-True
  - env-centipede_n-3_batchmode-True
  - env-centipede_n-4_batchmode-True
pong:
  - env-pong_n-2_batchmode-True
  - env-pong_n-3_batchmode-True
  - env-pong_n-4_batchmode-True
...
