---
toytext:
  xmetric: timestep
  ymetric: avg_return
  xlim: [0, 2000000]
  ylog: False
  xlabel: Timestep
  ylabel: Episode Return
  labels: [Uniform, Stratified]
  colors: [black, tab:blue]
  plots:
    taxi:
      title: Taxi
      experiments:
        - env-Taxi-v3_timesteps-2000000_rmemtype-ReplayMemory
        - env-Taxi-v3_timesteps-2000000_rmemtype-StratifiedReplayMemory
    frozenlake:
      title: FrozenLake
      experiments:
        - env-FrozenLake-v0_timesteps-2000000_rmemtype-ReplayMemory
        - env-FrozenLake-v0_timesteps-2000000_rmemtype-StratifiedReplayMemory
...
